[project]
name = "zydisk-player"
version = "1.0.0"
description = "Motion graphic presentation player"
readme = "README.md"
requires-python = ">=3.13"

dependencies = [
    "flet==0.86.2",
    "flet-video==0.86.2",
]

[tool.flet]
org = "com.zydisk"
product = "Zydisk Player"
company = "Zydisk"

[tool.flet.android]
split_per_abi = false

permissions = [
    "android.permission.READ_EXTERNAL_STORAGE",
    "android.permission.WRITE_EXTERNAL_STORAGE"
]
