name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  UV_PYTHON: "3.13"
  PYTHONUTF8: "1"
  FLET_CLI_NO_RICH_OUTPUT: "1"

jobs:
  build-apk:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v6

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          uv sync

      - name: Build APK
        run: |
          uv run flet build apk --yes --verbose

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: zydisk-player
          path: build/apk/
